# Generated by Django 5.2.4 on 2025-07-15 15:18

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(default="Staff Reporter", max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="is_editor_pick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
