# Generated by Django 5.2.4 on 2025-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_author_article_is_editor_pick_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="article",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Paste YouTube/Vimeo embed URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
