# Generated by Django 5.2.4 on 2025-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_video_article_video_url_alter_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
